/**
 * DIRECTIVE — Asset Pipeline & Derivation Rules §3 (binding, 2026-07-12):
 * "Regenerate ASSET_MANIFEST.md from the registry... Keep the manifest
 * generated from code from now on; hand-editing it is prohibited."
 *
 * Run via `npm run assets:manifest`. Reads src/game/assets/assetRegistry.ts
 * (the single source of truth) and writes docs/ASSET_MANIFEST.md as a
 * generated table — id, name, category, pipeline, sourceOrDerived,
 * derivedFrom, status. Never hand-edit the output file; edit the registry
 * and regenerate instead.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { ASSET_REGISTRY, derivedEntries, entriesByPipeline, sourceEntries } from "../src/game/assets/assetRegistry";
import { ASSET_PIPELINE_KINDS, COLOUR_LAW_SUBSTITUTIONS } from "../src/game/assets/assetPipeline";

function mdEscape(field: string): string {
  return field.replace(/\|/g, "\\|");
}

const byCategory = new Map<string, number>();
for (const e of ASSET_REGISTRY) byCategory.set(e.category, (byCategory.get(e.category) ?? 0) + 1);

const statusCounts = { missing: 0, placeholder: 0, delivered: 0 };
for (const e of ASSET_REGISTRY) statusCounts[e.status] += 1;

const lines: string[] = [];
lines.push("# AFTERLIGHT — Asset Registry Manifest (generated, do not hand-edit)");
lines.push("");
lines.push(
  "**Generated by `scripts/generate-asset-manifest.ts` from `src/game/assets/assetRegistry.ts` — the registry is the source of truth.** " +
    "Run `npm run assets:manifest` to regenerate after any registry change. Per DIRECTIVE §3, this file is never hand-edited.",
);
lines.push("");
lines.push(
  "Three pipelines (DIRECTIVE §1): **keyed** (pre-keyed RGBA PNGs — ships/enemies/boss/commander sprites, pickups, and every icon-shaped asset), " +
    "**additive** (RGB-on-black, rendered with a `lighter` composite — VFX, status effects, mutation tells, tier rings, rarity frames), " +
    "**fullbleed** (opaque backgrounds — biomes, UI screens, briefings, star-map art).",
);
lines.push("");
lines.push(
  "Derived assets (DIRECTIVE §2) are never separate source files — ship roster thumbnails, enemy move/attack/death states, and the World-Ender/Vanguard boss variants " +
    "are all generated in code from a real parent asset (see `derivedFrom`). They still appear below (status tracking covers them too) but never need their own art file.",
);
lines.push("");

lines.push("## Summary");
lines.push("");
lines.push(`- **Total registry entries: ${ASSET_REGISTRY.length}**`);
lines.push(`- **True source-file count (excludes derived): ${sourceEntries().length}**`);
lines.push(`- Derived (code-generated, no art file needed): ${derivedEntries().length}`);
lines.push(
  `- By pipeline: keyed ${entriesByPipeline("keyed").length}, additive ${entriesByPipeline("additive").length}, fullbleed ${entriesByPipeline("fullbleed").length}`,
);
lines.push(`- By status: missing ${statusCounts.missing}, placeholder ${statusCounts.placeholder}, delivered ${statusCounts.delivered}`);
lines.push("");
lines.push(
  "**Colour law (DIRECTIVE §4):** nothing green in any KEYED sprite's palette (the chroma-key extraction step would strip it). " +
    `Substitutions: ${Object.entries(COLOUR_LAW_SUBSTITUTIONS).map(([k, v]) => `${k} → ${v}`).join(", ")}. ` +
    "Green is permitted freely in additive/fullbleed assets. Crystal Dominion sprites are magenta-keyed instead of green-keyed (see each entry's own `keyColour`).",
);
lines.push("");

lines.push("## By category");
lines.push("");
lines.push("| Category | Count |");
lines.push("|---|---|");
for (const [category, count] of [...byCategory.entries()].sort()) lines.push(`| ${category} | ${count} |`);
lines.push("");

lines.push("## Full registry");
lines.push("");
lines.push("| id | name | category | pipeline | sourceOrDerived | derivedFrom | status |");
lines.push("|---|---|---|---|---|---|---|");
for (const e of ASSET_REGISTRY) {
  lines.push(`| ${mdEscape(e.id)} | ${mdEscape(e.name)} | ${e.category} | ${e.pipeline} | ${e.sourceOrDerived} | ${e.derivedFrom ? mdEscape(e.derivedFrom) : ""} | ${e.status} |`);
}
lines.push("");

const outPath = path.resolve(import.meta.dirname, "../docs/ASSET_MANIFEST.md");
fs.writeFileSync(outPath, lines.join("\n") + "\n");

console.log(`Wrote ${outPath}`);
console.log(`TOTAL registry entries: ${ASSET_REGISTRY.length}`);
console.log(`TRUE SOURCE-FILE COUNT: ${sourceEntries().length}`);
console.log(`Derived (no art file needed): ${derivedEntries().length}`);
for (const pipeline of ASSET_PIPELINE_KINDS) console.log(`  ${pipeline}: ${entriesByPipeline(pipeline).length}`);
