#!/usr/bin/env python3
"""
Achievement badge extraction from the user's "Achievement Badges" sheet (an
8-col x 4-row grid of icon+label cards on a flat near-black backdrop — no
real alpha, stripped via tools/_bgremove.strip_dark_background).

Crops each grid cell's icon area (excluding the printed label underneath),
removes the dark background, auto-trims to the resulting alpha bounding box,
re-encodes as a 160px-long-edge WebP data-URI, and emits
src/game/render/achievementRaster.ts, keyed by AchievementDef ids (see
achievementDefs.ts). Matched by name/theme where a badge clearly corresponds
to an existing achievement; the sheet has some badges with no current
in-game counterpart (Adaptive, Hidden Paths, Pet Lover, Team Player) and
achievementDefs.ts has more achievements than the sheet has badges — both
directions just fall back gracefully (painted-overrides-procedural-glyph).

Usage: python3 tools/achievementBadges.py   (from the repo root; needs
Pillow, numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_dark_background

SHEET = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be/4087f0a4-388B34BA8213497A9AFF9B7E56584942.png")
OUT = Path(__file__).resolve().parent.parent / "src/game/render/achievementRaster.ts"

GRID = (0, 90, 1536, 1024)  # (x0, y0, x1, y1) around the 8x4 badge grid
COLS, ROWS = 8, 4
ICON_FRAC_HEIGHT = 0.72  # crop off the printed label under each icon

# achievement id (see achievementDefs.ts) -> (col, row), 0-indexed.
CELLS = {
    "trailblazer": (0, 0),  # EXPLORER — compass
    "keeper": (1, 0),  # SURVIVOR — heart shield
    "collector": (2, 0),  # COLLECTOR — chest
    "hollowbane": (3, 0),  # HUNTER — skull crosshair
    "conqueror": (4, 0),  # CONQUEROR — trophy
    "quartermaster": (5, 0),  # ENGINEER — wrench gear
    "investor": (6, 0),  # TRADER — coins
    "veteran": (7, 0),  # CHAMPION — star shield
    "first-light": (0, 1),  # FIRST LIGHT — rocket
    "bossbreaker": (1, 1),  # WAVE CLEAR — cannon
    "boss-slayer": (2, 1),  # BOSS SLAYER — horned skull
    "deeplight": (3, 1),  # GALAXY WALKER — spiral galaxy
    "ascendant": (4, 1),  # ASCENDED — triangle
    "legion-ender": (5, 1),  # UNSTOPPABLE — skull wings
    "benefactor": (6, 1),  # BIG SPENDER — crystal hoard
    "paragon": (7, 1),  # LUCKY STAR — gold star
    "iron-vigil": (0, 2),  # NO DAMAGE — blue shield
    "storm-rider": (1, 2),  # SPEED RUNNER — stopwatch
    "prospector": (2, 2),  # RESOURCEFUL — green crystals
    "warlord": (3, 2),  # OVERPOWERED — crossed cannons
    "centennial": (4, 2),  # PERFECTIONIST — ribbon medal
    "dreadbane": (6, 2),  # DESTRUCTION — explosion
    "voidfarer": (7, 2),  # VOID WALKER — purple ring portal
    "devotee": (0, 3),  # DEDICATED — calendar
    "golden-wake": (1, 3),  # RETURNING LIGHT — glowing plant
    "champion-hunter": (3, 3),  # ELITE HUNTER — skull banner
    "salvager": (6, 3),  # LEGENDARY FIND — gold gem chest
    "eternal-flame": (7, 3),  # ETERNAL LEGEND — crowned gem
}


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(col, row, inset=0.08):
    im = Image.open(SHEET).convert("RGBA")
    gx0, gy0, gx1, gy1 = GRID
    cw, ch = (gx1 - gx0) / COLS, (gy1 - gy0) / ROWS
    x0, y0 = gx0 + col * cw + cw * inset, gy0 + row * ch + ch * inset
    x1 = gx0 + (col + 1) * cw - cw * inset
    y1 = gy0 + row * ch + ch * ICON_FRAC_HEIGHT
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_dark_background(cell)
    return autocrop_alpha(cell)


def to_webp_datauri(im, target_long_edge, quality=88):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = [
        "/**",
        " * Painted achievement badge icons (user-supplied AFTERLIGHT",
        " * character-sheet delivery, cropped per element in-repo). WebP",
        " * data-URIs so they bundle for offline/single-file builds. Not every",
        " * achievement has a matching badge (and vice versa) — UIManager falls",
        " * back to the procedural glyphIcon() for any id missing here.",
        " * Generated by tools/achievementBadges.py.",
        " */",
        "export const ACHIEVEMENT_RASTER: Record<string, string> = {",
    ]
    for ach_id, (col, row) in CELLS.items():
        cell = grid_cell(col, row)
        uri = to_webp_datauri(cell, 160)
        lines.append(f'  "{ach_id}":\n    "{uri}",')
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
