#!/usr/bin/env python3
"""
Alien-creature extraction for VANGUARD's regular (non-boss) Hollow enemies,
from the user's "Alien Creatures & Pickups" sheet (a 6-col x 4-row grid on a
flat near-black backdrop — no real alpha, stripped via
tools/_bgremove.strip_dark_background).

Crops each grid cell, removes the dark background, auto-trims to the
resulting alpha bounding box, re-encodes as a 320px-long-edge WebP data-URI,
and emits idle-game/src/game/render/three/alienCreatures.ts, keyed by
VANGUARD's EnemyShape ids (see idle-game/src/game/data/enemyDefs.ts).

Usage: python3 tools/alienCreatures.py   (from the repo root; needs Pillow,
numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_dark_background

SHEET = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be/1072fd22-F7AA56CA708840BD9C718BA9FDB9949F.png")
OUT = Path(__file__).resolve().parent.parent / "idle-game/src/game/render/three/alienCreatures.ts"

# Grid bounds (px, in the 1536x1024 source) around the 6x4 "ALIEN CREATURES"
# panel, calibrated by inspection.
GRID = (8, 45, 1122, 788)
COLS, ROWS = 6, 4

# EnemyShape id -> (col, row), 0-indexed.
CELLS = {
    "wraith": (0, 2),  # hooded skull-ghost with purple flame wisps
    "dome": (3, 0),  # blue octopus/jellyfish, tentacles
    "shard": (1, 3),  # blue crystal cluster on dark rock
    "brute": (2, 1),  # black spiky ball, big purple eye
    "darter": (1, 1),  # yellow/orange robot ball, twin antennae
    "robed": (2, 3),  # black horned ball, angry orange eyes
}


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(col, row, inset=0.05):
    im = Image.open(SHEET).convert("RGBA")
    gx0, gy0, gx1, gy1 = GRID
    cw, ch = (gx1 - gx0) / COLS, (gy1 - gy0) / ROWS
    x0, y0 = gx0 + col * cw + cw * inset, gy0 + row * ch + ch * inset
    x1, y1 = gx0 + (col + 1) * cw - cw * inset, gy0 + (row + 1) * ch - ch * inset
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_dark_background(cell)
    return autocrop_alpha(cell)


def to_webp_datauri(im, target_long_edge, quality=88):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii"), im.size


def main():
    lines = [
        "/**",
        " * Painted Hollow-creature art for VANGUARD's regular (non-boss)",
        " * encounters (user-supplied AFTERLIGHT character-sheet delivery,",
        " * cropped per element in-repo). WebP data-URIs so they bundle for",
        " * offline/single-file builds. Generated by tools/alienCreatures.py.",
        " */",
        'import type { EnemyShape } from "../../data/enemyDefs";',
        'import type { PaintedSprite } from "./paintedArt";',
        "",
        "export const ENEMY_SPRITES: Record<EnemyShape, PaintedSprite> = {",
    ]
    for shape_id, (col, row) in CELLS.items():
        cell = grid_cell(col, row)
        uri, (w, h) = to_webp_datauri(cell, 320)
        lines.append(f'  {shape_id}: {{ uri:\n    "{uri}",\n    aspect: {w / h:.5f} }},')
    lines.append("};")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
