#!/usr/bin/env python3
"""
Boss art extraction from the user's AFTERLIGHT character-sheet delivery (two
4x2 grids of crystalline "galaxy-core" creatures). The sheets have no real
alpha (fully opaque PNG) — each cell has a baked-in near-white "transparency
checkerboard" background, stripped here via tools/_bgremove.py.

Crops each grid cell, removes the checker background, auto-trims to the
resulting alpha bounding box, re-encodes as a 384px-long-edge WebP data-URI,
and emits src/game/render/bossRaster.ts, replacing the previous (also
user-supplied) boss art.

Usage: python3 tools/bossCreatures.py   (from the repo root; needs Pillow,
numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_checker_background

UP = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be")
SHEET_1 = UP / "4452e407-13AFBB13223F4F0B97315A9D04BAD678.png"
SHEET_2 = UP / "9007b0c4-243775B4DB4143E9AE7EB05E9056D759.png"
OUT = Path(__file__).resolve().parent.parent / "src/game/render/bossRaster.ts"

# boss id -> (sheet, column, row) in each 4-col x 2-row grid.
CELLS = {
    "theMaw": (SHEET_1, 1, 0),  # black-hole "eye" core — spiked mass, central void
    "theChoir": (SHEET_1, 2, 0),  # orbiting-planet ring — the "hovering ring" motif
    "thePyre": (SHEET_1, 3, 0),  # molten orange/yellow swirl
    "theForge": (SHEET_2, 0, 1),  # blocky golden fire-core, no tendrils
    "theSovereign": (SHEET_1, 0, 0),  # violet swirl ringed by shard-plates
    "theRime": (SHEET_1, 1, 1),  # icy cyan/blue swirl, four-legged stance
    "theNadir": (SHEET_1, 2, 1),  # compact blue single-ring, saturn-like
}


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(sheet_path, col, row, cols=4, rows=2, inset=0.02):
    im = Image.open(sheet_path).convert("RGBA")
    w, h = im.size
    cw, ch = w / cols, h / rows
    x0, y0 = col * cw + cw * inset, row * ch + ch * inset
    x1, y1 = (col + 1) * cw - cw * inset, (row + 1) * ch - ch * inset
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_checker_background(cell)
    return autocrop_alpha(cell)


def to_webp_datauri(im, target_long_edge, quality=85):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = [
        "/**",
        " * Painted boss art (user-supplied AFTERLIGHT character-sheet delivery,",
        " * cropped per element in-repo). WebP data-URIs so they bundle for offline/",
        " * single-file builds. Generated by tools/bossCreatures.py.",
        " */",
        "export const BOSS_RASTER: Record<string, string> = {",
    ]
    for boss_id, (sheet, col, row) in CELLS.items():
        cell = grid_cell(sheet, col, row)
        uri = to_webp_datauri(cell, 384)
        lines.append(f'  {boss_id}:\n    "{uri}",')
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
