#!/usr/bin/env python3
"""
Commander portrait extraction from the user's AFTERLIGHT character-sheet
delivery (a 4x2 grid of chibi pilot portraits). The sheet has no real alpha
(fully opaque PNG) — each cell has a baked-in near-white "transparency
checkerboard" background, stripped here via tools/_bgremove.py.

Crops each grid cell, removes the checker background, auto-trims to the
resulting alpha bounding box, re-encodes as a 320px-long-edge WebP data-URI,
and emits src/game/render/commanderRaster.ts. Portraits are matched to
WARDEN_LIST commanders by armor-accent colour; 8 of the 9 commanders got a
match (wren has none yet — keeps its procedural fallback until a matching
portrait arrives).

Usage: python3 tools/commanderPortraits.py   (from the repo root; needs
Pillow, numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_checker_background

UP = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be")
SHEET = UP / "67750283-5173515F482A40B6B0537080F275A0A1.png"
OUT = Path(__file__).resolve().parent.parent / "src/game/render/commanderRaster.ts"

# commander id (see wardenDefs.ts) -> (column, row) in the 4-col x 2-row grid.
CELLS = {
    "lumen": (0, 0),  # blue/white armor, "V" chest logo
    "rax": (1, 0),  # blonde, orange/white/black armor
    "mira": (2, 0),  # green accents, brown hair
    "vela": (3, 0),  # pink hair, purple/black armor
    "onyx": (0, 1),  # brown hair bun + glasses, white/gold armor
    "pyre": (1, 1),  # orange goggles, red/orange armor
    "vesper": (2, 1),  # silver hair, white/purple armor
    "surge": (3, 1),  # beard, navy/orange armor
    # "wren" has no matching portrait in this delivery yet.
}


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(sheet_path, col, row, cols=4, rows=2, inset=0.02):
    im = Image.open(sheet_path).convert("RGBA")
    w, h = im.size
    cw, ch = w / cols, h / rows
    x0, y0 = col * cw + cw * inset, row * ch + ch * inset
    x1, y1 = (col + 1) * cw - cw * inset, (row + 1) * ch - ch * inset
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_checker_background(cell)
    return autocrop_alpha(cell)


def to_webp_datauri(im, target_long_edge, quality=85):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = [
        "/**",
        " * Painted Commander portraits (user-supplied AFTERLIGHT character-sheet",
        " * delivery, cropped per element in-repo). WebP data-URIs so they bundle",
        " * for offline/single-file builds. Generated by tools/commanderPortraits.py.",
        " */",
        "export const COMMANDER_PORTRAITS: Record<string, string> = {",
    ]
    for commander_id, (col, row) in CELLS.items():
        cell = grid_cell(SHEET, col, row)
        uri = to_webp_datauri(cell, 320)
        lines.append(f'  {commander_id}:\n    "{uri}",')
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
