#!/usr/bin/env python3
"""
Commander portrait extraction from the user's AFTERLIGHT character-sheet
delivery. Two sources:

  1. A 4x2 grid of chibi pilot portraits (checker-background, see
     tools/_bgremove.strip_checker_background) — 8 of 9 commanders.
  2. The "Pilot Outfits & Costumes" sheet's Astro Engineer card (dark-
     background, see tools/_bgremove.strip_dark_background) for wren
     (hue 95, yellow-green) — the one commander with no match in (1).

Crops each, removes its backdrop, auto-trims to the resulting alpha
bounding box, re-encodes as a 320px-long-edge WebP data-URI, and emits
src/game/render/commanderRaster.ts.

Usage: python3 tools/commanderPortraits.py   (from the repo root; needs
Pillow, numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import keep_largest_component, strip_checker_background, strip_dark_background

UP = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be")
PORTRAIT_SHEET = UP / "67750283-5173515F482A40B6B0537080F275A0A1.png"
OUTFIT_SHEET = UP / "96923b8c-0E43CEE766214B8BA0B893F705C1C9D0.png"
OUT = Path(__file__).resolve().parent.parent / "src/game/render/commanderRaster.ts"

# commander id (see wardenDefs.ts) -> (column, row) in the 4-col x 2-row grid.
CELLS = {
    "lumen": (0, 0),  # blue/white armor, "V" chest logo
    "rax": (1, 0),  # blonde, orange/white/black armor
    "mira": (2, 0),  # green accents, brown hair
    "vela": (3, 0),  # pink hair, purple/black armor
    "onyx": (0, 1),  # brown hair bun + glasses, white/gold armor
    "pyre": (1, 1),  # orange goggles, red/orange armor
    "vesper": (2, 1),  # silver hair, white/purple armor
    "surge": (3, 1),  # beard, navy/orange armor
}


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(sheet_path, col, row, cols=4, rows=2, inset=0.02):
    im = Image.open(sheet_path).convert("RGBA")
    w, h = im.size
    cw, ch = w / cols, h / rows
    x0, y0 = col * cw + cw * inset, row * ch + ch * inset
    x1, y1 = (col + 1) * cw - cw * inset, (row + 1) * ch - ch * inset
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_checker_background(cell)
    return autocrop_alpha(cell)


def wren_cell():
    # Astro Engineer card, generously cropped (calibrated by inspection) so
    # the backpack device isn't clipped, then de-speckled: a wide crop this
    # close to a neighbouring card's border picks up stray chrome (a corner
    # star icon, the divider line) as small disconnected islands.
    im = Image.open(OUTFIT_SHEET).convert("RGBA")
    cell = im.crop((0, 590, 320, 850))
    cell = strip_dark_background(cell, brightness_thresh=55, feather=1.0)
    cell = keep_largest_component(cell)
    return autocrop_alpha(cell, pad_frac=0.02)


def to_webp_datauri(im, target_long_edge, quality=85):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = [
        "/**",
        " * Painted Commander portraits (user-supplied AFTERLIGHT character-sheet",
        " * delivery, cropped per element in-repo). WebP data-URIs so they bundle",
        " * for offline/single-file builds. Generated by tools/commanderPortraits.py.",
        " */",
        "export const COMMANDER_PORTRAITS: Record<string, string> = {",
    ]
    for commander_id, (col, row) in CELLS.items():
        cell = grid_cell(PORTRAIT_SHEET, col, row)
        uri = to_webp_datauri(cell, 320)
        lines.append(f'  {commander_id}:\n    "{uri}",')
    uri = to_webp_datauri(wren_cell(), 320)
    lines.append(f'  wren:\n    "{uri}",')
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
