#!/usr/bin/env python3
"""
Currency icon extraction for VANGUARD's top-bar chips, from the user's
AFTERLIGHT flash-sheet delivery (dark backdrop, stripped via
tools/_bgremove.strip_dark_background):

  Light Motes -> the "Light Mote" gold crystal (exact name match).
  Afterglow   -> the "Time Sphere" portal/orb (eternal/permanent-power vibe
                 fits VANGUARD's prestige currency).

Alloy keeps its plain glyph — none of the sheet's crystal icons reads as
"salvaged metal," so forcing one in would be a worse fit than the glyph.

Emits idle-game/src/ui/currencyIcons.ts as WebP data-URIs (bundled for
offline/single-file builds).

Usage: python3 tools/vanguardCurrency.py   (from the repo root; needs
Pillow, numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_dark_background

SHEET = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be/37ca749c-022A116A12694D94BFB36014F94D1BAC.png")
OUT = Path(__file__).resolve().parent.parent / "idle-game/src/ui/currencyIcons.ts"

CROPS = {
    "LIGHT_MOTE_ICON": (15, 105, 155, 225),
    "AFTERGLOW_ICON": (615, 90, 758, 220),
}


def extract(box):
    im = Image.open(SHEET).convert("RGBA")
    cell = im.crop(box)
    cell = strip_dark_background(cell)
    bbox = cell.split()[-1].getbbox()
    pad = 4
    x0, y0, x1, y1 = bbox
    x0, y0 = max(0, x0 - pad), max(0, y0 - pad)
    x1, y1 = min(cell.width, x1 + pad), min(cell.height, y1 + pad)
    return cell.crop((x0, y0, x1, y1))


def to_webp_datauri(im, target_long_edge, quality=90):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = [
        "/**",
        " * Painted currency icons for the top-bar chips (user-supplied",
        " * AFTERLIGHT flash-sheet delivery, cropped per element in-repo).",
        " * WebP data-URIs so they bundle for offline/single-file builds.",
        " * Generated by tools/vanguardCurrency.py.",
        " */",
    ]
    for const_name, box in CROPS.items():
        uri = to_webp_datauri(extract(box), 96)
        lines.append(f'export const {const_name} =\n  "{uri}";')
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
