#!/usr/bin/env python3
"""
Real-art extraction for VANGUARD (idle-game/): reuses the same AFTERLIGHT
character-sheet delivery as tools/bossCreatures.py and
tools/commanderPortraits.py, cropping the hero portrait and two boss
creatures for use as camera-facing sprite billboards in the WebGL scene
(idle-game/src/game/render/three/Scene3D.ts), replacing the primitive
geometry rigs for just the hero and bosses.

Emits idle-game/src/game/render/three/paintedArt.ts.

Usage: python3 tools/vanguardArt.py   (from the repo root; needs Pillow,
numpy, scipy)
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bgremove import strip_checker_background

UP = Path("/root/.claude/uploads/8d4c5166-d731-5037-83be-9215c8d1b4be")
PORTRAIT_SHEET = UP / "67750283-5173515F482A40B6B0537080F275A0A1.png"
BOSS_SHEET_1 = UP / "4452e407-13AFBB13223F4F0B97315A9D04BAD678.png"
OUT = Path(__file__).resolve().parent.parent / "idle-game/src/game/render/three/paintedArt.ts"


def autocrop_alpha(im, pad_frac=0.04):
    bbox = im.split()[-1].getbbox()
    if not bbox:
        return im
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px, py = int(w * pad_frac), int(h * pad_frac)
    x0, y0 = max(0, x0 - px), max(0, y0 - py)
    x1, y1 = min(im.width, x1 + px), min(im.height, y1 + py)
    return im.crop((x0, y0, x1, y1))


def grid_cell(sheet_path, col, row, cols, rows, inset=0.02):
    im = Image.open(sheet_path).convert("RGBA")
    w, h = im.size
    cw, ch = w / cols, h / rows
    x0, y0 = col * cw + cw * inset, row * ch + ch * inset
    x1, y1 = (col + 1) * cw - cw * inset, (row + 1) * ch - ch * inset
    cell = im.crop((int(x0), int(y0), int(x1), int(y1)))
    cell = strip_checker_background(cell)
    return autocrop_alpha(cell)


def to_webp_datauri(im, target_long_edge, quality=88):
    w, h = im.size
    scale = target_long_edge / max(w, h)
    im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="WEBP", quality=quality, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    hero = grid_cell(PORTRAIT_SHEET, 0, 0, 4, 2)  # blue/white "V" commander — the Vanguard
    maw = grid_cell(BOSS_SHEET_1, 1, 0, 4, 2)  # black-hole "eye" core
    choir = grid_cell(BOSS_SHEET_1, 2, 0, 4, 2)  # orbiting-planet ring

    hero_uri, (hw, hh) = to_webp_datauri(hero, 360), hero.size
    maw_uri, (mw, mh) = to_webp_datauri(maw, 420), maw.size
    choir_uri, (cw, ch) = to_webp_datauri(choir, 420), choir.size

    lines = [
        "/**",
        " * Painted art (user-supplied AFTERLIGHT character-sheet delivery, cropped",
        " * per element in-repo) used as camera-facing sprite billboards for the",
        " * hero and boss encounters — see Scene3D.ts. Regular (non-boss) Hollow",
        " * enemies still use the primitive rigs in Rig.ts. WebP data-URIs so they",
        " * bundle for offline/single-file builds. Generated by tools/vanguardArt.py.",
        " */",
        "export interface PaintedSprite {",
        "  uri: string;",
        "  /** Source aspect ratio (width / height), for correctly-proportioned billboards. */",
        "  aspect: number;",
        "}",
        "",
        f'export const HERO_PORTRAIT: PaintedSprite = {{ uri: "{hero_uri}", aspect: {hw / hh:.5f} }};',
        "",
        "export const BOSS_SPRITES: Record<\"maw\" | \"choir\", PaintedSprite> = {",
        f'  maw: {{ uri: "{maw_uri}", aspect: {mw / mh:.5f} }},',
        f'  choir: {{ uri: "{choir_uri}", aspect: {cw / ch:.5f} }},',
        "};",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
